[pytest]
pythonpath = .
filterwarnings =
    ignore:'oneOf' deprecated - use 'one_of':DeprecationWarning:matplotlib\._fontconfig_pattern
    ignore:'parseString' deprecated - use 'parse_string':DeprecationWarning:matplotlib\._fontconfig_pattern
    ignore:'resetCache' deprecated - use 'reset_cache':DeprecationWarning:matplotlib\._fontconfig_pattern
    ignore:'enablePackrat' deprecated - use 'enable_packrat':DeprecationWarning:matplotlib\._mathtext
    ignore:Converting `np.inexact` or `np.floating` to a dtype is deprecated:DeprecationWarning:shap\.plots\.colors\._colorconv
    ignore:Could not find the number of physical cores for the following reason:UserWarning:joblib\.externals\.loky\.backend\.context
